members_list({ "next_cursor" : 0,
  "next_cursor_str" : "0",
  "previous_cursor" : 0,
  "previous_cursor_str" : "0",
  "users" : [ { "contributors_enabled" : false,
        "created_at" : "Fri Sep 18 22:28:18 +0000 2009",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "Father, Husband, Design Lead at BörseGo. User Experience, Interface/Webdesign, Technology. Loves to smoke Cigar's. And a MacUser.",
        "favourites_count" : 191,
        "follow_request_sent" : null,
        "followers_count" : 220,
        "following" : null,
        "friends_count" : 107,
        "geo_enabled" : true,
        "id" : 75403530,
        "id_str" : "75403530",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 10,
        "location" : "Germany / Munich",
        "name" : "Sven Read",
        "notifications" : null,
        "profile_background_color" : "131516",
        "profile_background_image_url" : "http://a1.twimg.com/images/themes/theme14/bg.gif",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme14/bg.gif",
        "profile_background_tile" : true,
        "profile_image_url" : "http://a0.twimg.com/profile_images/960125238/10417_100356933317855_100000306455159_6279_3465843_n_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/960125238/10417_100356933317855_100000306455159_6279_3465843_n_normal.jpg",
        "profile_link_color" : "009999",
        "profile_sidebar_border_color" : "eeeeee",
        "profile_sidebar_fill_color" : "efefef",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "StarBurst1977",
        "show_all_inline_media" : true,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 14:03:30 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170508674031304704,
            "id_str" : "170508674031304704",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "possibly_sensitive" : false,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://www.apple.com\" rel=\"nofollow\">Safari on iOS</a>",
            "text" : "Do no evil?  http://t.co/UFCWO6cg",
            "truncated" : false
          },
        "statuses_count" : 6634,
        "time_zone" : "Berlin",
        "url" : "http://www.svenread.com",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Sat Jan 21 21:25:59 +0000 2012",
        "default_profile" : true,
        "default_profile_image" : false,
        "description" : "Civil Engineer, Ruby developer, Mac addicted, ...",
        "favourites_count" : 3,
        "follow_request_sent" : false,
        "followers_count" : 5,
        "following" : false,
        "friends_count" : 44,
        "geo_enabled" : false,
        "id" : 470527085,
        "id_str" : "470527085",
        "is_translator" : false,
        "lang" : "de",
        "listed_count" : 1,
        "location" : "Munich, Germany",
        "name" : "Tobias L. Maier",
        "notifications" : false,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a0.twimg.com/profile_images/1771563752/IMG_3392_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1771563752/IMG_3392_normal.jpg",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "tobias_maier",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Tue Feb 14 13:38:31 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 169415223629979649,
            "id_str" : "169415223629979649",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "possibly_sensitive" : false,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://twitter.com/tweetbutton\" rel=\"nofollow\">Tweet Button</a>",
            "text" : "Nice Presentation: Scaling GitHub http://t.co/ZLATXvyE",
            "truncated" : false
          },
        "statuses_count" : 5,
        "time_zone" : "Berlin",
        "url" : "http://www.tobiasmaier.info",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Tue Jul 24 13:13:09 +0000 2007",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "UX Designer, Entrepreneur.",
        "favourites_count" : 26,
        "follow_request_sent" : false,
        "followers_count" : 500,
        "following" : false,
        "friends_count" : 853,
        "geo_enabled" : true,
        "id" : 7682812,
        "id_str" : "7682812",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 5,
        "location" : "Munich",
        "name" : "Jose E. G. Modecir",
        "notifications" : false,
        "profile_background_color" : "ffffff",
        "profile_background_image_url" : "http://a0.twimg.com/profile_background_images/2461495/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/profile_background_images/2461495/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a3.twimg.com/profile_images/1591805543/DSC_0371_copy-1_normal.JPG",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1591805543/DSC_0371_copy-1_normal.JPG",
        "profile_link_color" : "73A824",
        "profile_sidebar_border_color" : "B7BC97",
        "profile_sidebar_fill_color" : "E6E5D2",
        "profile_text_color" : "444444",
        "profile_use_background_image" : false,
        "protected" : false,
        "screen_name" : "tank6b",
        "show_all_inline_media" : false,
        "statuses_count" : 1395,
        "time_zone" : "Berlin",
        "url" : "http://nlapse.com",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Mon Jul 20 20:40:47 +0000 2009",
        "default_profile" : true,
        "default_profile_image" : false,
        "description" : "",
        "favourites_count" : 2,
        "follow_request_sent" : null,
        "followers_count" : 60,
        "following" : null,
        "friends_count" : 125,
        "geo_enabled" : true,
        "id" : 58583995,
        "id_str" : "58583995",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 1,
        "location" : "Munich",
        "name" : "Sonia Fabre",
        "notifications" : null,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a0.twimg.com/profile_images/1295136878/Picture_15_normal.png",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1295136878/Picture_15_normal.png",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "soniafabre",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 09:30:04 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170439864200863744,
            "id_str" : "170439864200863744",
            "in_reply_to_screen_name" : "refreshmunich",
            "in_reply_to_status_id" : 170418109746921472,
            "in_reply_to_status_id_str" : "170418109746921472",
            "in_reply_to_user_id" : 426473473,
            "in_reply_to_user_id_str" : "426473473",
            "place" : { "attributes" : {  },
                "bounding_box" : { "coordinates" : [ [ [ 11.360588999999999,
                            48.061636
                          ],
                          [ 11.722918,
                            48.061636
                          ],
                          [ 11.722918,
                            48.248123999999997
                          ],
                          [ 11.360588999999999,
                            48.248123999999997
                          ]
                        ] ],
                    "type" : "Polygon"
                  },
                "country" : "Germany",
                "country_code" : "DE",
                "full_name" : "Munich, Munich",
                "id" : "b694c6c2f0f05db2",
                "name" : "Munich",
                "place_type" : "city",
                "url" : "http://api.twitter.com/1/geo/id/b694c6c2f0f05db2.json"
              },
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "web",
            "text" : "@refreshmunich Too bad I missed this one. See you guys in May!",
            "truncated" : false
          },
        "statuses_count" : 117,
        "time_zone" : null,
        "url" : null,
        "utc_offset" : null,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Wed Aug 19 14:23:40 +0000 2009",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "engineer // still pre phd // kinda crazy & always online!",
        "favourites_count" : 0,
        "follow_request_sent" : false,
        "followers_count" : 118,
        "following" : false,
        "friends_count" : 240,
        "geo_enabled" : true,
        "id" : 67012360,
        "id_str" : "67012360",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 11,
        "location" : "48.13507,11.570059",
        "name" : "el loco - Dirk Haage",
        "notifications" : false,
        "profile_background_color" : "FFFFFF",
        "profile_background_image_url" : "http://a3.twimg.com/profile_background_images/153367501/x8cfbcef666100b67626181caba877a3.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/profile_background_images/153367501/x8cfbcef666100b67626181caba877a3.png",
        "profile_background_tile" : true,
        "profile_image_url" : "http://a3.twimg.com/profile_images/701652107/f32a0f6ae85c7c7d926846e1d74523297df035ef_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/701652107/f32a0f6ae85c7c7d926846e1d74523297df035ef_normal.jpg",
        "profile_link_color" : "5D83BB",
        "profile_sidebar_border_color" : "919191",
        "profile_sidebar_fill_color" : "FFFFFF",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "e110c0",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 00:37:27 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170305825804521472,
            "id_str" : "170305825804521472",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
            "text" : "can't wait for the fixed UIs of calendar and contacts in #mountainlion #osx",
            "truncated" : false
          },
        "statuses_count" : 1733,
        "time_zone" : "Berlin",
        "url" : "http://dirk.haage.info",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Fri Mar 21 20:45:38 +0000 2008",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "",
        "favourites_count" : 0,
        "follow_request_sent" : null,
        "followers_count" : 13,
        "following" : null,
        "friends_count" : 64,
        "geo_enabled" : false,
        "id" : 14193503,
        "id_str" : "14193503",
        "is_translator" : false,
        "lang" : "de",
        "listed_count" : 1,
        "location" : "Munich",
        "name" : "marcorei",
        "notifications" : null,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a0.twimg.com/profile_images/1472754905/profilbild3null_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1472754905/profilbild3null_normal.jpg",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : false,
        "protected" : false,
        "screen_name" : "marcorei",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Sat Feb 11 14:59:48 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 168348514470989824,
            "id_str" : "168348514470989824",
            "in_reply_to_screen_name" : "JoggaF",
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : 49598333,
            "in_reply_to_user_id_str" : "49598333",
            "place" : null,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://twitter.com/#!/download/ipad\" rel=\"nofollow\">Twitter for iPad</a>",
            "text" : "@JoggaF Hab grad die Star Wars Kinect Demo gespielt. High Potential ;)",
            "truncated" : false
          },
        "statuses_count" : 130,
        "time_zone" : "Greenland",
        "url" : null,
        "utc_offset" : -10800,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Tue Nov 09 08:16:03 +0000 2010",
        "default_profile" : true,
        "default_profile_image" : false,
        "description" : "Software engineer loving life- and productivity-hacking, HTML5, movies and the flexibility my android phone gives me to check everything no matter where I'm.",
        "favourites_count" : 63,
        "follow_request_sent" : null,
        "followers_count" : 58,
        "following" : null,
        "friends_count" : 96,
        "geo_enabled" : false,
        "id" : 213578079,
        "id_str" : "213578079",
        "is_translator" : false,
        "lang" : "de",
        "listed_count" : 3,
        "location" : "Munich",
        "name" : "Michael Westrich",
        "notifications" : null,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a3.twimg.com/profile_images/1591606446/IMG_2543_twitter_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1591606446/IMG_2543_twitter_normal.jpg",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "gr1lly",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 11:37:16 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170471871559639040,
            "id_str" : "170471871559639040",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "retweet_count" : 2,
            "retweeted" : false,
            "retweeted_status" : { "contributors" : null,
                "coordinates" : null,
                "created_at" : "Fri Feb 17 10:25:33 +0000 2012",
                "favorited" : false,
                "geo" : null,
                "id" : 170453826485227520,
                "id_str" : "170453826485227520",
                "in_reply_to_screen_name" : null,
                "in_reply_to_status_id" : null,
                "in_reply_to_status_id_str" : null,
                "in_reply_to_user_id" : null,
                "in_reply_to_user_id_str" : null,
                "place" : null,
                "retweet_count" : 2,
                "retweeted" : false,
                "source" : "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
                "text" : "Great Stammtisch last night with all the @refreshmunich folks and newly joined @StarBurst1977 - can't wait for the next one :-)",
                "truncated" : false
              },
            "source" : "<a href=\"https://chrome.google.com/extensions/detail/encaiiljifbdbjlphpgpiimidegddhic\" rel=\"nofollow\">Silver Bird</a>",
            "text" : "RT @jng5: Great Stammtisch last night with all the @refreshmunich folks and newly joined @StarBurst1977 - can't wait for the next one :-)",
            "truncated" : false
          },
        "statuses_count" : 510,
        "time_zone" : "Berlin",
        "url" : null,
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Mon Jun 22 11:06:37 +0000 2009",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "Hey, I tweet about design (especially interface design), politics, innovation, culture, art & personal stuff.",
        "favourites_count" : 23,
        "follow_request_sent" : null,
        "followers_count" : 62,
        "following" : null,
        "friends_count" : 191,
        "geo_enabled" : false,
        "id" : 49598333,
        "id_str" : "49598333",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 2,
        "location" : "Munich, Germany",
        "name" : "Joachim Fröstl",
        "notifications" : null,
        "profile_background_color" : "ffffff",
        "profile_background_image_url" : "http://a2.twimg.com/profile_background_images/46945425/Twitter.jpg",
        "profile_background_image_url_https" : "https://si0.twimg.com/profile_background_images/46945425/Twitter.jpg",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a0.twimg.com/profile_images/1210051841/Kanten_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1210051841/Kanten_normal.jpg",
        "profile_link_color" : "1d9898",
        "profile_sidebar_border_color" : "ffffff",
        "profile_sidebar_fill_color" : "ffffff",
        "profile_text_color" : "333333",
        "profile_use_background_image" : false,
        "protected" : false,
        "screen_name" : "JoggaF",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 08:20:56 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170422463480594432,
            "id_str" : "170422463480594432",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "retweet_count" : 50,
            "retweeted" : false,
            "retweeted_status" : { "contributors" : null,
                "coordinates" : null,
                "created_at" : "Fri Feb 17 07:37:13 +0000 2012",
                "favorited" : false,
                "geo" : null,
                "id" : 170411464295854081,
                "id_str" : "170411464295854081",
                "in_reply_to_screen_name" : null,
                "in_reply_to_status_id" : null,
                "in_reply_to_status_id_str" : null,
                "in_reply_to_user_id" : null,
                "in_reply_to_user_id_str" : null,
                "place" : null,
                "retweet_count" : 50,
                "retweeted" : false,
                "source" : "<a href=\"http://www.echofon.com/\" rel=\"nofollow\">Echofon</a>",
                "text" : "\"@Staatsanwaltschaft_Hannover just ousted @Christian_Wulff as the mayor of Schloss Bellevue on @foursquare!\"",
                "truncated" : false
              },
            "source" : "web",
            "text" : "RT @bachleitner: \"@Staatsanwaltschaft_Hannover just ousted @Christian_Wulff as the mayor of Schloss Bellevue on @foursquare!\"",
            "truncated" : false
          },
        "statuses_count" : 374,
        "time_zone" : "Berlin",
        "url" : null,
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Tue Oct 05 23:17:13 +0000 2010",
        "default_profile" : true,
        "default_profile_image" : false,
        "description" : "UI/UX Designer & Marketing Student",
        "favourites_count" : 1,
        "follow_request_sent" : false,
        "followers_count" : 22,
        "following" : false,
        "friends_count" : 53,
        "geo_enabled" : true,
        "id" : 199064716,
        "id_str" : "199064716",
        "is_translator" : false,
        "lang" : "de",
        "listed_count" : 1,
        "location" : "",
        "name" : "Dana Nedamaldeen",
        "notifications" : false,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a1.twimg.com/profile_images/1790135152/407477_2753703526005_1360178929_32538679_966288812_n_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1790135152/407477_2753703526005_1360178929_32538679_966288812_n_normal.jpg",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "DanaNeda",
        "show_all_inline_media" : false,
        "statuses_count" : 164,
        "time_zone" : "Greenland",
        "url" : null,
        "utc_offset" : -10800,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Sat Jun 28 22:04:09 +0000 2008",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "Software developer based in beautiful Munich, Germany. Creator of Piqtur. ",
        "favourites_count" : 82,
        "follow_request_sent" : null,
        "followers_count" : 231,
        "following" : null,
        "friends_count" : 96,
        "geo_enabled" : true,
        "id" : 15266337,
        "id_str" : "15266337",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 18,
        "location" : "Munich, Germany",
        "name" : "Elias Klughammer",
        "notifications" : null,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/profile_background_images/174302148/bgGrainGray.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/profile_background_images/174302148/bgGrainGray.png",
        "profile_background_tile" : true,
        "profile_image_url" : "http://a2.twimg.com/profile_images/1790637317/Elias1_normal.png",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1790637317/Elias1_normal.png",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "eliaskg",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 11:59:47 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170477540144717825,
            "id_str" : "170477540144717825",
            "in_reply_to_screen_name" : "jng5",
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : 139345833,
            "in_reply_to_user_id_str" : "139345833",
            "place" : null,
            "possibly_sensitive" : false,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://twitterrific.com\" rel=\"nofollow\">Twitterrific for Mac</a>",
            "text" : "@jng5 @sebslomski @dana @refreshmunich Anyone interested in an UI Sketchbook? They give shipping discount for 3+ books: http://t.co/mNy2Bcnq",
            "truncated" : false
          },
        "statuses_count" : 2410,
        "time_zone" : "Berlin",
        "url" : "http://www.elias.kg",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Tue Apr 26 07:33:02 +0000 2011",
        "default_profile" : true,
        "default_profile_image" : false,
        "description" : "Living the future!",
        "favourites_count" : 24,
        "follow_request_sent" : null,
        "followers_count" : 90,
        "following" : null,
        "friends_count" : 136,
        "geo_enabled" : true,
        "id" : 288100592,
        "id_str" : "288100592",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 5,
        "location" : "Munich",
        "name" : "Sebastian Slomski",
        "notifications" : null,
        "profile_background_color" : "C0DEED",
        "profile_background_image_url" : "http://a0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_image_url_https" : "https://si0.twimg.com/images/themes/theme1/bg.png",
        "profile_background_tile" : false,
        "profile_image_url" : "http://a1.twimg.com/profile_images/1701830938/313743_2328442863992_1637330090_2436746_988141074_n_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1701830938/313743_2328442863992_1637330090_2436746_988141074_n_normal.jpg",
        "profile_link_color" : "0084B4",
        "profile_sidebar_border_color" : "C0DEED",
        "profile_sidebar_fill_color" : "DDEEF6",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "sebslomski",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 14:23:06 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170513607308746753,
            "id_str" : "170513607308746753",
            "in_reply_to_screen_name" : null,
            "in_reply_to_status_id" : null,
            "in_reply_to_status_id_str" : null,
            "in_reply_to_user_id" : null,
            "in_reply_to_user_id_str" : null,
            "place" : null,
            "possibly_sensitive" : false,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "web",
            "text" : "Mojang is creating a game and live streaming it for 60 hours. Live. Stream. - http://t.co/9HfCd1Ta",
            "truncated" : false
          },
        "statuses_count" : 1352,
        "time_zone" : "Berlin",
        "url" : "http://sebslomski.com",
        "utc_offset" : 3600,
        "verified" : false
      },
      { "contributors_enabled" : false,
        "created_at" : "Sun May 02 09:26:42 +0000 2010",
        "default_profile" : false,
        "default_profile_image" : false,
        "description" : "Designer, runner and entrepreneur, tinkering in all things web and user experience - grüß di!",
        "favourites_count" : 101,
        "follow_request_sent" : false,
        "followers_count" : 183,
        "following" : false,
        "friends_count" : 142,
        "geo_enabled" : true,
        "id" : 139345833,
        "id_str" : "139345833",
        "is_translator" : false,
        "lang" : "en",
        "listed_count" : 10,
        "location" : "Munich, Germany",
        "name" : "Julie Ng",
        "notifications" : false,
        "profile_background_color" : "B2DFDA",
        "profile_background_image_url" : "http://a2.twimg.com/profile_background_images/238817764/brauneck2_21-37-57.jpg",
        "profile_background_image_url_https" : "https://si0.twimg.com/profile_background_images/238817764/brauneck2_21-37-57.jpg",
        "profile_background_tile" : true,
        "profile_image_url" : "http://a2.twimg.com/profile_images/1699894976/falkenstein-portrait-sq_normal.jpg",
        "profile_image_url_https" : "https://si0.twimg.com/profile_images/1699894976/falkenstein-portrait-sq_normal.jpg",
        "profile_link_color" : "93A644",
        "profile_sidebar_border_color" : "eeeeee",
        "profile_sidebar_fill_color" : "ffffff",
        "profile_text_color" : "333333",
        "profile_use_background_image" : true,
        "protected" : false,
        "screen_name" : "jng5",
        "show_all_inline_media" : false,
        "status" : { "contributors" : null,
            "coordinates" : null,
            "created_at" : "Fri Feb 17 10:28:00 +0000 2012",
            "favorited" : false,
            "geo" : null,
            "id" : 170454442573955072,
            "id_str" : "170454442573955072",
            "in_reply_to_screen_name" : "JoggaF",
            "in_reply_to_status_id" : 170245651261693952,
            "in_reply_to_status_id_str" : "170245651261693952",
            "in_reply_to_user_id" : 49598333,
            "in_reply_to_user_id_str" : "49598333",
            "place" : null,
            "retweet_count" : 0,
            "retweeted" : false,
            "source" : "<a href=\"http://itunes.apple.com/us/app/twitter/id409789998?mt=12\" rel=\"nofollow\">Twitter for Mac</a>",
            "text" : "@JoggaF schade, aber bis zum nächsten Stammtisch oder Lunch :-)",
            "truncated" : false
          },
        "statuses_count" : 1052,
        "time_zone" : "Berlin",
        "url" : "http://www.julieng.me",
        "utc_offset" : 3600,
        "verified" : false
      }
    ]
});