
baseurl:     /
port:        4000
url:         http://localhost:4000

source:      .
destination: ./_site
permalink:   date
future:      false

repo_url:   http://github.com/refreshmunich/website
pages_url:  http://refreshmunich.com/